
obj-$(CONFIG_RTL8367_PHY) += port.o
obj-$(CONFIG_RTL8367_PHY) += rtk_switch.o
obj-$(CONFIG_RTL8367_PHY) += rtl8367c_asicdrv.o
obj-$(CONFIG_RTL8367_PHY) += rtl8367c_asicdrv_green.o
obj-$(CONFIG_RTL8367_PHY) += rtl8367c_asicdrv_inbwctrl.o
obj-$(CONFIG_RTL8367_PHY) += rtl8367c_asicdrv_lut.o
obj-$(CONFIG_RTL8367_PHY) += rtl8367c_asicdrv_mirror.o
obj-$(CONFIG_RTL8367_PHY) += rtl8367c_asicdrv_misc.o
obj-$(CONFIG_RTL8367_PHY) += rtl8367c_asicdrv_phy.o
obj-$(CONFIG_RTL8367_PHY) += rtl8367c_asicdrv_port.o
obj-$(CONFIG_RTL8367_PHY) += rtl8367c_asicdrv_portIsolation.o
obj-$(CONFIG_RTL8367_PHY) += rtl8367c_asicdrv_rma.o
obj-$(CONFIG_RTL8367_PHY) += rtl8367c_asicdrv_scheduling.o
obj-$(CONFIG_RTL8367_PHY) += smi.o
