FILESEXTRAPATHS_prepend :="${THISDIR}/files:"
SRC_URI_append += " file://xserver-nodm.service.in "
SYSTEMD_AUTO_ENABLE_${PN} = "enable"
PACKAGECONFIG_remove = "blank"
PACKAGECONFIG_append = " nocursor"
